menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# Enable / Disable menu icons / item badges.
menu_settings:
  icons: true
  badges: true
  
scheme: Pisces

codeblock:
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Show text copy result.
    show_result: true

giscus:
  enable: true
  repo: liuxingjun/liuxingjun.github.io # Github repository name
  repo_id: R_kgDOHD5VgQ # Github repository id
  category: Announcements # Github discussion category
  category_id: DIC_kwDOHD5Vgc4CT8mY # Github discussion category id
  # Available values: pathname | url | title | og:title
  mapping: og:title
  # Available values: 0 | 1
  reactions_enabled: 1
   # Available values: 0 | 1
  emit_metadata: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: preferred_color_scheme
  # Available values: en | zh-CN
  lang: zh-CN
  # Place the comment box above the comments
  input_position: bottom
  # Load the comments lazily
  loading: lazy