name: Pages

on:
  push:
    branches:
      - master  # default branch
    paths:
      - 'scaffolds/**'
      - 'source/**'
      - 'themes/**'
      - '_config*.yaml'
      - '.github/**'
  # 手动执行
  workflow_dispatch:
jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js 13.x
        uses: actions/setup-node@v2
        with:
          node-version: '13'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm ci
      # - name: checkout public
      #   uses: actions/checkout@v3
      #   with:
      #     ref: gh-pages
      #     path: public
      - name: Build
        run: npm run build
      - run: cd public &&  git status && git diff css/main.css
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          commit_message: ${{ github.event.head_commit.message }}
